kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
  namespace: test  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: ravindrasingh6969/myapp
        ports:
        - containerPort: 8080
